[tool.poetry]
name = "gensim_w2v"
version = "0.1.0"
description = ""
authors = ["hjmr <2620990+hjmr@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
gensim = "*"
scikit-learn = "*"
japanize-matplotlib = "*"
mecab = "*"
bs4 = "*"
requests = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
