[tool.poetry]
name = "gensim_word2vec"
version = "0.1.0"
description = ""
authors = ["Hajime Murao <2620990+hjmr@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
matplotlib = "^3.1.3"
janome = "^0.3.10"
gensim = "^3.8.1"
scikit-learn = "^0.22.1"
mecab-python3 = "^0.996.3"
japanize-matplotlib = "^1.0.5"

[tool.poetry.dev-dependencies]
pylint = "^2.4.4"
autopep8 = "^1.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
