[tool.poetry]
name = "gensim_word2vec"
version = "0.1.0"
description = ""
authors = ["Hajime Murao <2620990+hjmr@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
matplotlib = "^3.5.1"
janome = "^0.4.2"
japanize-matplotlib = "^1.1.3"
mecab = "^0.996.3"
gensim = "^4.1.2"
scikit-learn = "^1.0.2"

[tool.poetry.dev-dependencies]
pylint = "^2.13.2"
black = "^22.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
